image: ruby:2.6

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - mkdir public
  - sudo apt-get node install
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - CSE340-SP19-FINAL
  tags:
  - Pages
