image: ruby:2.4

cache:
  paths:
  - vendor/
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  JEKYLL_ENV: production 

before_script:
  - mkdir public
  - bundle install --path vendor

pages:
  stage: deploy
  script:
  - env LANG=\"en_US.UTF-8\" bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - CSE340-SP19-FINAL
  tags:
  - Pages

