# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Interaction Programming (CSE 340)
description: Interactive Tech is changing society. Help invent the future!
baseurl: "" # use relative url instead
relativeurls: true
url: "https://jmankoff.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jcmankoff
github_username:  jmankoff
piazza: "https://piazza.com/washington/spring2019/cse340/"
canvas: "https://canvas.uw.edu/courses/1317447"
gitlab: "http://gitlab.cs.washington.edu/cse340/19sp"
hcibook: "[UI textbook](https://www.amazon.com/dp/1423902483/ref=rdr_ext_sb_ti_hist_1)"
androidbook: "[Android textbook](https://www.amazon.com/dp/1977540090/ref=rdr_ext_tmb)"
paginate:            5

author:
    name: jmankoff
    url: "http://make4all.org/"

email: "jmankoff@acm.org"            # Your contact email
  # probably want to update this to be the class teaching staff mailing list

# The Reveal theme
reveal_theme: black.css

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-assets
  - uglifier
  - jekyll-mermaid
  - jekyll-font-awesome-sass
  
highlighter: rouge

bootstrap:
    assets: true
    
assets:
    digest: false
    prefix: "/assets"
    sources:
        - "*"

sass:
  sass_dir: "./_scss"
#  style: compressed

kramdown:
  toc_levels: '1'

mermaid:
  src: '/interaction/assets/js/mermaid.js'
  src_config: '/interaction/assets/js/mermaid_config.js'
  
remarkConfig:
  # possible highlight options:
  # arta, ascetic, dark, default, far, github, googlecode, idea, ir_black,
  # magula, monokai, rainbow, solarized-dark, solarized-light, sunburst,
  # tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night,
  # tomorrow-night-eighties, vs, zenburn.
  highlightStyle: 'solarized-light'
  highlightLanguage: 'remark'
  highlightLines: true

# Logic for a projects collection page
collections:
  slides:
    permalink: /rivera-lab/:path/
    output: true

# Custom vars
version:             1.0.0

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

font-awesome:
  assets: true