# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Interaction Programming (CSE 340)
description: Interactive Tech is changing society. Help invent the future!
baseurl: "/interaction" # the subpath of your site, e.g. /blog
url: "https://jmankoff.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jcmankoff
github_username:  jmankoff
paginate:            5

author:
    name: jmankoff
    url: "http://make4all.org/"

email: "jmankoff@acm.org"            # Your contact email
  # probably want to update this to be the class teaching staff mailing list

# The Reveal theme
reveal_theme: black.css

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass
  - jekyll-paginate
  - jekyll-redirect-from

highlighter: rouge

assets:
    prefix: "/assets"
    sources:
        - "*"


sass:
  sass_dir: _sass

remarkConfig:
  # possible highlight options:
  # arta, ascetic, dark, default, far, github, googlecode, idea, ir_black,
  # magula, monokai, rainbow, solarized-dark, solarized-light, sunburst,
  # tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night,
  # tomorrow-night-eighties, vs, zenburn.
  highlightStyle: 'solarized-light'
  highlightLanguage: 'remark'
  highlightLines: true

# Logic for a projects collection page
collections:
  slides:
    permalink: /rivera-lab/:path/
    output: true

# Custom vars
version:             1.0.0

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
